### ISSUE TITLE
Some unicode glitching.

### ISSUE THREAD

**Issue by Pomax** [j0e1in/MasterClassDownloader#2]
It looks like the downloader has some issues with unicode - for Gordon Ramsay's series, for instance, I just ran into this error:

```bash
Wait for 300 seconds...
12 videos left
[Wistia] ubsn00lwm7: Downloading JSON metadata
[download] Destination: Lectures\Gordon Ramsay-Cooking\9-109_GR_Demo_CookwithGordonChickenSuprêmewithRootVegetables_v4_ForDelivery_v2.mp4
[download] 100% of 1.87GiB in 03:58
Traceback (most recent call last):
  File "video-dl.py", line 57, in <module>
    main()
  File "video-dl.py", line 49, in main
    print("Finished downloading {}\n".format(info['title']))
  File "C:\Python35\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0302' in position 59: character maps to <undefined>
```
which looks to be about the `ê` in `9-109_GR_Demo_CookwithGordonChickenSuprêmewithRootVegetables_v4_ForDelivery_v2.mp4`, where that's actually the plain `e` followed by `U+0302 COMBINING CIRCUMFLEX ACCENT : hat`

It actually downloaded just fine, and the filename is correct, but this error does make the downloader crash out, so you can't resume "past" it either. It'll just run through 1-9 and then crash on 9 again.

(using python 3.5 on windows)

**Comment by Pomax** [comment]
Looks like it's a python version issue, so filing a PR for the readme.

**Comment by j0e1in** [comment]
Thanks for the report. 
However, I don't have this problem on Ubuntu 18.04, python 3.5.5.
It seems like Windows-specific issue.
Does python 3.6 work for you? I can update readme to alert windows users to use python 3.6.

**Comment by Pomax** [comment]
Yeah, apparently 3.6 changed the behaviour so that even in Windows the codepage is always UTF-8 unless someone intentionally changed it. So simply being on 3.6+ fixes it.
